run:
  concurrency: 4
  deadline: 10m
  issues-exit-code: 1
  tests: true # include test files or not
  skip-dirs-use-default: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk # checks for dangerous unicode character sequences
    - bodyclose
    - dogsled # checks assignments with too many blank identifiers ('_')
    - dupl
    - errcheck
    - errname
    - funlen
    - gocognit # checks how hard does the code is intuitively to understand
    - goconst
    - gocyclo
    - gosec
    - ineffassign
    - interfacebloat
    - lll
    - misspell
    - nestif
    - nilerr
    - nonamedreturns
    - prealloc
    - predeclared
    - unconvert

linters-settings:
  dogsled:
    max-blank-identifiers: 2
  dupl:
    threshold: 100 # tokens count to trigger issue
  errcheck:
    check-type-assertions: true # report about not checking of errors in type assertions
    check-blank: true # report about assignment of errors to blank identifier ('_')
  funlen:
    lines: 100
    statements: 75
  gocognit:
    min-complexity: 10
  goconst:
    min-len: 3
    min-occurrences: 2
    ignore-tests: false
    match-constant: true
  gocyclo:
    min-complexity: 15
  gosec:
    exclude-generated: true
    severity: medium
    includes:
      - G101 # Look for hard coded credentials
      - G106 # Audit the use of ssh.InsecureIgnoreHostKey
      - G107 # Url provided to HTTP request as taint input
      - G110 # Potential DoS vulnerability via decompression bomb
      - G114 # Use of net/http serve function that has no support for setting timeouts
      - G202 # SQL query construction using string concatenation
      - G401 # Detect the usage of DES, RC4, MD5 or SHA
      - G402 # Look for bad TLS connection settings
      - G403 # Ensure minimum RSA key length of 2048 bits
      - G404 # Insecure random number source (rand) 
  interfacebloat:
    max: 6
  lll:
    line-length: 140
    tab-width: 4 # tab width in spaces
  misspell:
    locale: US
  nestif:
    min-complexity: 5
  nonamedreturns:
    report-error-in-defer: true
  prealloc:
    simple: false
    range-loops: true
    for-loops: true
