run:
  timeout: 3m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - bodyclose
    - cyclop
    - dogsled
    - funlen
    - gosec
    - gci
    - goconst
    - interfacebloat
    - lll
    - nestif
    - nlreturn
    
linters-settings:
  errcheck:
    check-type-assertions: true
  cyclop:
    skip-tests: true
  dogsled:
    max-blank-identifiers: 2
  funlen:
    lines: 30
  gosec:
    exclude-generated: true
    severity: medium
    includes:
      - G101 # Look for hard coded credentials
      - G103 # Audit the use of unsafe block
      - G104 # Audit errors not checked
      - G106 # Audit the use of ssh.InsecureIgnoreHostKey
      - G107 # Url provided to HTTP request as taint input
      - G109 # Potential Integer overflow made by strconv.Atoi result conversion to int16/32
      - G110 # Potential DoS vulnerability via decompression bomb
      - G114 # Use of net/http serve function that has no support for setting timeouts
      - G201 # SQL query construction using format string
      - G202 # SQL query construction using string concatenation
      - G203 # Use of unescaped data in HTML templates
      - G204 # Audit use of command execution
      - G307 # Deferring a method which returns an error
      - G401 # Detect the usage of DES, RC4, MD5 or SHA
      - G402 # Look for bad TLS connection settings
      - G403 # Ensure minimum RSA key length of 2048 bits
      - G404 # Insecure random number source (rand)
  gci:
    skip-generated: false
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/org/project)
  goconst:
    match-constant: true
    min-len: 2
    min-occurrences: 3
    ignore-tests: true
    ignore-calls: true
    numbers: true
  interfacebloat:
    max: 6
  lll:
    line-length: 100
  nestif:
    min-complexity: 3

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true